stages:
  - IAC
  - dag-logic
  # - build-image
  # - destroygit stats
  # - default

variables:
  REGION: $REGION
  AWS_PARTITION: aws-cn
  ROLE_ARN: arn:aws-cn:iam::$AWS_ACCOUNT_ID:role/team-account-deploy-gitlabscaniacomcn-dbt
  AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID
  DOCKER_HOST: tcp://docker:2375  # This environment variable sets the address of the Docker daemon for the pipeline to communicate with. It tells the CI job to use a remote Docker daemon available at the specified TCP address.
  DOCKER_TLS_CERTDIR: "" #This environment variable disables the use of Docker's TLS certificate directory for secure connections to the Docker daemon.Docker-in-Docker (DinD) by default uses TLS for security, but setting this to an empty string disables TLS for simplicity during CI/CD execution. It's typically done in a trusted environment where security of the Docker daemon communication isn't a concern.
  ECR_URL: $ECR_URL
  SNOWFLAKE_ACCOUNT: $SNOWFLAKE_ACCOUNT
  SNOWFLAKE_USER: $SNOWFLAKE_USER
  #donot declare sensitive variables.
  SNOWFLAKE_PASSWORD: $SNOWFLAKE_PASSWORD
  repo_name: $repo_name
  bucket_name: $bucket_name
# Either we need cache or either we clean - rm -rf ./IAC/root/.terraform. if need both then use cache in stage not here......。
# cache: # The cache keyword in GitLab pipelines is used to specify files or directories that should be cached between jobs or pipeline runs. This caches the .terraform directory under the specified path (./IAC/root/), which contains Terraform's initialized backend files and downloaded provider plugins.Using the cache avoids re-downloading these files in subsequent pipeline runs, saving time and reducing external dependencies.
#   paths:
#     - ./IAC/root/.terraform

default:
  # image: "registry.gitlab.scania.com.cn/datalake/dbt-project:latest"
  image:
    name: "public.ecr.aws/bitnami/aws-cli:latest"   #before commands use default image
    entrypoint: [""]  
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.scania.com.cn

.assume_role:
  - aws --version
  - >
    export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s"
    $(aws sts assume-role-with-web-identity
    --role-arn $ROLE_ARN
    --role-session-name "GitLabRunner-$CI_PROJECT_ID-$CI_PIPELINE_ID"
    --web-identity-token $GITLAB_OIDC_TOKEN
    --duration-seconds 3600
    --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
    --region $REGION
    --output text))
  - aws sts get-caller-identity --region $REGION

# before_script:

#   - echo "aws sts assume-role-with-web-identity --role-arn $ROLE_ARN --role-session-name \"GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}\" --web-identity-token $GITLAB_OIDC_TOKEN --duration-seconds 3600 --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --region $REGION --output text"
#   - export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $(aws sts assume-role-with-web-identity --role-arn $ROLE_ARN --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}" --web-identity-token $GITLAB_OIDC_TOKEN --duration-seconds 3600 --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' --region $REGION --output text))
  #- rm -rf ./IAC/root/.terraform # The .terraform directory is functioning correctly, and you want to save time by reusing cached files. In a CI/CD pipeline, however: A fresh start ensures consistency and avoids unexpected errors caused by stale files. This is particularly important in shared environments or automated workflows.
  #- echo "ECR repository name: $repo_name"

IAC:
  stage: IAC
  image: public.ecr.aws/hashicorp/terraform:1.13.0-alpha20250521
  script:
    # - aws s3 ls
    - terraform -chdir=./IAC/root init
    #- terraform -chdir=./IAC/root plan -out="planfile" -var="env_var=[{\"name\":\"SNOWFLAKE_ACCOUNT\",\"value\":\"$SNOWFLAKE_ACCOUNT\"},{\"name\":\"SNOWFLAKE_USER\",\"value\":\"$SNOWFLAKE_USER\"},{\"name\":\"SNOWFLAKE_PASSWORD\",\"value\":\"$SNOWFLAKE_PASSWORD\"}]"
    #- repo_name=$(echo "$repo_name" | tr -cd 'a-z0-9._-' | tr -d '[:space:]')
    - terraform -chdir=./IAC/root plan -out="planfile" -var="env_var=[{\"name\":\"SNOWFLAKE_ACCOUNT\",\"value\":\"$SNOWFLAKE_ACCOUNT\"},{\"name\":\"SNOWFLAKE_USER\",\"value\":\"$SNOWFLAKE_USER\"},{\"name\":\"SNOWFLAKE_PASSWORD\",\"value\":\"$SNOWFLAKE_PASSWORD\"}]" -var="s3_bucket_name=$bucket_name" -var="ecr_repository_name=$repo_name"
    # - terraform -chdir=./IAC/root apply -input=false --auto-approve "planfile"
    # - terraform -chdir=./IAC/root output -json > terraform_outputs.json
    #- cat terraform_outputs.json
  artifacts:
    paths:
      - terraform_outputs.json
  # only:
  #   changes:
  #     - IAC/**/*

dag-logic:
  stage: dag-logic
  before_script:
    - !reference [.assume_role]
  script:
    - ls -l
    - pwd
    #- cat terraform_outputs.json
    - aws s3 ls
    - chmod +x update_dag.sh
    - ./update_dag.sh
    - cat dbt_ecs_task.py
    - aws s3 ls s3://$bucket_name/dags/
  # only:
  #   changes:
  #     - IAC/**/*


# build-image:
#   stage: build-image
#   services:
#     - name: "public.ecr.aws/b4p2j5t6/dind:latest"  # Use the custom dind image......
#       alias: docker
#   script:
#     - docker info
#     - docker build -t $repo_name -f ./project/Dockerfile ./project
#     - aws ecr get-login-password --region $REGION| docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.cn-northwest-1.amazonaws.com.cn 
#     - docker tag $repo_name:latest $ECR_URL/$repo_name:latest
#     - docker push $ECR_URL/$repo_name:latest
#   # only:
#   #   changes:
#   #     - project/**/*
  
# destroy:
#   stage: destroy
#   script:
#     - |
#       aws s3api list-object-versions --bucket $bucket_name \
#         --query "Versions[].[Key,VersionId]" --output text | while read key version_id; do
#           aws s3api delete-object --bucket $bucket_name \
#             --key "$key" --version-id "$version_id"
#         done > /dev/null 2>&1 || true
#     - aws ecr batch-delete-image --repository-name $repo_name --image-ids imageTag=latest > /dev/null 2>&1 || true
#     - terraform -chdir=./IAC/root init
#     - terraform -chdir=./IAC/root plan -out="planfile" -var="env_var=[{\"name\":\"SNOWFLAKE_ACCOUNT\",\"value\":\"$SNOWFLAKE_ACCOUNT\"},{\"name\":\"SNOWFLAKE_USER\",\"value\":\"$SNOWFLAKE_USER\"},{\"name\":\"SNOWFLAKE_PASSWORD\",\"value\":\"$SNOWFLAKE_PASSWORD\"}]" -var="ecr_repository_name=$repo_name" -var="s3_bucket_name=$bucket_name"
#     #- terraform -chdir=./IAC/root plan -out="planfile" -var="env_var=[{\"name\":\"SNOWFLAKE_ACCOUNT\",\"value\":\"$SNOWFLAKE_ACCOUNT\"},{\"name\":\"SNOWFLAKE_USER\",\"value\":\"$SNOWFLAKE_USER\"},{\"name\":\"SNOWFLAKE_PASSWORD\",\"value\":\"$SNOWFLAKE_PASSWORD\"}]"
#     - terraform -chdir=./IAC/root destroy -var="env_var=[{\"name\":\"SNOWFLAKE_ACCOUNT\",\"value\":\"$SNOWFLAKE_ACCOUNT\"},{\"name\":\"SNOWFLAKE_USER\",\"value\":\"$SNOWFLAKE_USER\"},{\"name\":\"SNOWFLAKE_PASSWORD\",\"value\":\"$SNOWFLAKE_PASSWORD\"}]" -var="ecr_repository_name=$repo_name" -var="s3_bucket_name=$bucket_name" --auto-approve
#     #- terraform -chdir=./IAC/root destroy -var="env_var=[{\"name\":\"SNOWFLAKE_ACCOUNT\",\"value\":\"$SNOWFLAKE_ACCOUNT\"},{\"name\":\"SNOWFLAKE_USER\",\"value\":\"$SNOWFLAKE_USER\"},{\"name\":\"SNOWFLAKE_PASSWORD\",\"value\":\"$SNOWFLAKE_PASSWORD\"}]" --auto-approve
#     #- terraform -chdir=./IAC/root destroy # #
#   when: manual

# default:
#   stage: default
#   script:
#     - echo "No significant changes detected"
#   except:
#     changes:
#       - IAC/**/*   # Ignore IaC changes
#       - project/**/*   # Ignore project changes..