demo_dbt:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: SHARAFAT_maximo_test
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: ACCOUNTADMIN
      schema: PUBLIC
      thread: 1
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: TEST_WAREHOUSE
  target: dev

#   #You can reuse the same profiles.yml file for different environments (e.g., dev, prod) by changing only the environment variables in git lab.
#   #You're using env_var in your profiles.yml file for secure and flexible configuration of your dbt environment.